import requests
import pprint
pp = pprint.PrettyPrinter(indent=2)


# This is an example query as it is generated by the rppo package
# https://biscicol.org/api/v3/download/_search?q=+dayOfYear:<=1++AND+++dayOfYear:<=100++AND+++latitude:>=-130+AND++latitude:<=40+AND++longitude:>=-130+AND++longitude:<=-110++AND+++source:USA-NPN&limit=2

# This works:
query_test = "https://biscicol.org/api/v1/query/_search?pretty&size=1&q=genus:Quercus"
query_test = "https://biscicol.org/api/v1/query/_search?pretty&size=1&q=genus:Syringa AND source:PEP725 AND year:[2000 TO 2021]"

r = requests.get(query_test)
pp.pprint(r.json())


# This doesn't work:
url = "https://biscicol.org/api/v1/query/_search?pretty&scroll=1m"
data = {
    "from": 0, 
    "size": 10,
    "_source": ["latitude", "longitude", "dayOfYear", "year", "source"],
    "query": {
        "bool": {
              "must": [
                    { "match": { "genus":  "Quercus" }},
                    { "match": { "source":  "PEP725" }},
                    { "match": { "year":  "2007" }}
              ]
        }
    }
}
r = requests.get(url, params=data)
r

# This also doesn't work
data = {
    "query": {
        "query_string": {
            "query": "genus:Syringa AND source:PEP725 AND year:[2000 TO 2021]"
        }
    }
}

r = requests.get(url, params=data)
r
